basePath: /
definitions:
  schemas.ComputerCreateSchema:
    properties:
      id_room:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server todo server. You can visit the GitHub repository
    at https://github.com/LordGhostX/swag-gin-demo
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: UNICyber-API
  version: "1.0"
paths:
  /:
    get:
      operationId: index
      produces:
      - text/html
      responses:
        "200":
          description: OK
      summary: Get Docs API
  /api/v1/computer:
    post:
      operationId: create-computer
      parameters:
      - description: todo data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.ComputerCreateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: add a new item to the computers
swagger: "2.0"
