basePath: /
definitions:
  models.Response:
    properties:
      Data: {}
      Message:
        type: string
      Success:
        type: boolean
    type: object
  schemas.ComputerCreateSchema:
    properties:
      id_room:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  schemas.ComputerLabCreateSchema:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  schemas.ComputerLabUpdateSchema:
    properties:
      description:
        type: string
      name:
        description: Data
        type: string
    required:
    - description
    - name
    type: object
  schemas.ComputerUpdateSchema:
    properties:
      message:
        type: string
      name:
        description: Data
        type: string
      pos_x:
        description: UI
        type: number
      pos_y:
        type: number
      state:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server todo server. You can visit the GitHub repository
    at https://github.com/LordGhostX/swag-gin-demo
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: UNICyber-API
  version: "1.0"
paths:
  /api/v1/computer:
    delete:
      operationId: delete-computer
      parameters:
      - description: ID of Computer
        in: path
        name: id-computer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: delete a item of the computers
      tags:
      - Computer
    get:
      operationId: get-computer
      parameters:
      - description: ID of Computer
        in: path
        name: id-computer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: get a item of the computers
      tags:
      - Computer
    post:
      operationId: create-computer
      parameters:
      - description: Schema by Create New Computer
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.ComputerCreateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: add a new item of the computers
      tags:
      - Computer
    put:
      operationId: put-computer
      parameters:
      - description: ID of Computer
        in: path
        name: id-computer
        required: true
        type: string
      - description: Schema by Update New Computer
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.ComputerUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: update a item of the computers
      tags:
      - Computer
  /api/v1/computer-lab:
    delete:
      operationId: delete-computer-lab
      parameters:
      - description: ID del item
        in: path
        name: id-computer-lab
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: delete a item of the computer-lab
      tags:
      - Computer Lab
    get:
      operationId: get-computer-lab
      parameters:
      - description: ID of ComputerLab
        in: path
        name: id-computer-lab
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: get a item of the computer-lab
      tags:
      - Computer Lab
    post:
      operationId: create-computer-lab
      parameters:
      - description: Schema by Create New Computer Lab
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.ComputerLabCreateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: add a new item of the computer-lab
      tags:
      - Computer Lab
    put:
      operationId: put-computer-lab
      parameters:
      - description: ID del item
        in: path
        name: id-computer-lab
        required: true
        type: string
      - description: Schema by Update New Computer Lab
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.ComputerLabUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: update a item of the computer-lab
      tags:
      - Computer Lab
swagger: "2.0"
